FROM nvidia/cuda:12.6.2-cudnn-runtime-ubuntu22.04

RUN apt-get update && apt-get -y install sudo && apt-get install build-essential -y --no-install-recommends gcc
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 git -y 
RUN sudo apt install net-tools && apt-get install vim -y
RUN apt install curl -y && apt install wine -y &&  apt install wget && apt-get install -y iputils-ping
RUN sudo apt install iproute2 -y
USER root

# COPY settings.json /root/Documents/AirSim/settings.json
# WORKDIR /app
# ARG USERNAME=appuser
# RUN adduser --disabled-password --gecos "" $USERNAME && chown -R $USERNAME /app

# RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && chmod 0440 /etc/sudoers.d/$USERNAME
# USER $USERNAME
# ENV DISPLAY=host.docker.internal:0.0