[agent]
action_type = continuous


[infer]
load_from = logs/itmo/NH/ddpg-FixRates-z2/saved_weights/
logg_tb_dir = logs/itmo/NH/ddpg-FixRates-z2/infer/

[train]
load_from = ./logs/itmo/NH/ddpg-FixRates-z/saved_weights/
hidden_gru = 48
lr_critic = 7e-4
lr_actor = 1e-4

batch = 64
buffer_size = 50_000
min_replay_size = 1000
train_rate = 200
gradient_steps = 200
max_steps_per_episode = 800
tau = 5e-3
gamma = 0.99
seq_size = 5
clip_action = -2.5,2.5
velocity_size = 3
; velocity is 3 as: x y z -- strict for now 
random = 0.2

[logg]
save_weights = ./logs/itmo/NH/ddpg-FixZ/saved_weights/
logg_tb_dir = ./logs/itmo/NH/ddpg-FixZ/
logging_interval = 200
