[agent]
action_type = continuous


[infer]
load_from = 
logg_tb_dir = 

[train]
load_from = logs/itmo/NH/ddpg-newR2-2/saved_weights/
hidden_gru = 48
lr_critic = 3e-5
lr_actor = 3e-5
batch = 64
buffer_size = 50_000
min_replay_size = 2000

max_steps_per_episode = 300
tau = 5e-3
gamma = 0.99
seq_size = 5
clip_action = -2.5,2.5
velocity_size = 3
; velocity is 3 as: x y z -- strict for now 
train_rate = 5
random = 0.5

[logg]
save_weights = ./logs/itmo/NH/ddpg-newR2-3/saved_weights/
logg_tb_dir = ./logs/itmo/NH/ddpg-newR2-3/
logging_interval = 200
