[agent]
action_type = continuous


[infer]
load_from = 
logg_tb_dir = logs/test/infer/ddpn_no_per2/

[train]
load_from = 
hidden_gru = 48
lr_critic = 5e-4
lr_actor = 1e-4
batch = 32
buffer_size = 30_000
min_replay_size = 40
tau = 2e-3
gamma = 0.99
seq_size = 5
clip_action = -1.5,1.5
velocity_size = 3
train_rate = 4


[logg]
save_weights = ./saved_weights/test/ddpg
logg_tb_dir = ./logs/test/ddpg
logging_interval = 50
#500
